# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinearTui < Formula
  desc "Terminal user interface for Linear"
  homepage "https://github.com/roeyazroel/linear-tui"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roeyazroel/linear-tui/releases/download/v0.11.0/linear-tui_0.11.0_darwin_amd64.tar.gz"
      sha256 "a10f194c8115cbd27d840200aabe1273fb1f49b425bae0106ae708b29052ecac"

      define_method(:install) do
        bin.install "linear-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roeyazroel/linear-tui/releases/download/v0.11.0/linear-tui_0.11.0_darwin_arm64.tar.gz"
      sha256 "589c6fd73b10ed7357703471c7e2653f43792c3e17a8088247f76a0da3e9f43a"

      define_method(:install) do
        bin.install "linear-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roeyazroel/linear-tui/releases/download/v0.11.0/linear-tui_0.11.0_linux_amd64.tar.gz"
      sha256 "54d8c4a8f54ab8733e4f3f92d74e5af77f850ab27250ee5ea690262efa577b2a"
      define_method(:install) do
        bin.install "linear-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roeyazroel/linear-tui/releases/download/v0.11.0/linear-tui_0.11.0_linux_arm64.tar.gz"
      sha256 "6ec10b3fa0b474d587df505532fbba76e585ff04000b6be6f6fd9df46ab457b8"
      define_method(:install) do
        bin.install "linear-tui"
      end
    end
  end

  test do
    system "#{bin}/linear-tui", "--version"
  end
end
